package com.example.demo.repository;

import com.example.demo.entity.domain.Face;
import com.example.demo.entity.domain.FaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FaceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	long countByExample(FaceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int deleteByExample(FaceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int deleteByPrimaryKey(Long faceSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int insert(Face record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int insertSelective(Face record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	List<Face> selectByExampleWithBLOBs(FaceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	List<Face> selectByExample(FaceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	Face selectByPrimaryKey(Long faceSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int updateByExampleSelective(@Param("record") Face record, @Param("example") FaceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") Face record, @Param("example") FaceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int updateByExample(@Param("record") Face record, @Param("example") FaceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int updateByPrimaryKeySelective(Face record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Face record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FACE
	 * @mbg.generated  Sat Nov 30 13:59:54 JST 2019
	 */
	int updateByPrimaryKey(Face record);
}