package com.example.demo.entity.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Face {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FACE.FACE_SEQ
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	private Long faceSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FACE.FACE_GENDER
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	private String faceGender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FACE.FACE_AGE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	private BigDecimal faceAge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FACE.FACE_HAPPINESS
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	private BigDecimal faceHappiness;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FACE.FACE_SMILE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	private Integer faceSmile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FACE.ENTER_DATE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	private Date enterDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FACE.FACE_IMAGE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	private byte[] faceImage;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FACE.FACE_SEQ
	 * @return  the value of FACE.FACE_SEQ
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public Long getFaceSeq() {
		return faceSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FACE.FACE_SEQ
	 * @param faceSeq  the value for FACE.FACE_SEQ
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public void setFaceSeq(Long faceSeq) {
		this.faceSeq = faceSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FACE.FACE_GENDER
	 * @return  the value of FACE.FACE_GENDER
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public String getFaceGender() {
		return faceGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FACE.FACE_GENDER
	 * @param faceGender  the value for FACE.FACE_GENDER
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public void setFaceGender(String faceGender) {
		this.faceGender = faceGender == null ? null : faceGender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FACE.FACE_AGE
	 * @return  the value of FACE.FACE_AGE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public BigDecimal getFaceAge() {
		return faceAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FACE.FACE_AGE
	 * @param faceAge  the value for FACE.FACE_AGE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public void setFaceAge(BigDecimal faceAge) {
		this.faceAge = faceAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FACE.FACE_HAPPINESS
	 * @return  the value of FACE.FACE_HAPPINESS
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public BigDecimal getFaceHappiness() {
		return faceHappiness;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FACE.FACE_HAPPINESS
	 * @param faceHappiness  the value for FACE.FACE_HAPPINESS
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public void setFaceHappiness(BigDecimal faceHappiness) {
		this.faceHappiness = faceHappiness;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FACE.FACE_SMILE
	 * @return  the value of FACE.FACE_SMILE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public Integer getFaceSmile() {
		return faceSmile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FACE.FACE_SMILE
	 * @param faceSmile  the value for FACE.FACE_SMILE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public void setFaceSmile(Integer faceSmile) {
		this.faceSmile = faceSmile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FACE.ENTER_DATE
	 * @return  the value of FACE.ENTER_DATE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public Date getEnterDate() {
		return enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FACE.ENTER_DATE
	 * @param enterDate  the value for FACE.ENTER_DATE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public void setEnterDate(Date enterDate) {
		this.enterDate = enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FACE.FACE_IMAGE
	 * @return  the value of FACE.FACE_IMAGE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public byte[] getFaceImage() {
		return faceImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FACE.FACE_IMAGE
	 * @param faceImage  the value for FACE.FACE_IMAGE
	 * @mbg.generated  Sat Nov 30 03:12:55 JST 2019
	 */
	public void setFaceImage(byte[] faceImage) {
		this.faceImage = faceImage;
	}
}